# Production deployment

services:
  app:

    ports: ["80:80"]
    environment:
      ENVIRONMENT: prod
    
    build:
      context: .
    
  database:
    image: postgres:17

    ports: ["5432:5432"]
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d

    environment:
      # TODO: Can we not hard code this into the compose file?
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default