// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const schema = process.env["PRISMA_SCHEMA"] ?? "prisma/schema.prisma";
const migrationsPath =
  process.env["PRISMA_MIGRATIONS_PATH"] ?? "prisma/migrations";

export default defineConfig({
  schema,
  migrations: {
    path: migrationsPath,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
