services:
  database:
    image: postgres:14
    ports: ["5432:5432"]

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - ./data:/mnt/data
      - ./ddl:/docker-entrypoint-initdb.d